mysite/food/urls.py
from django.urls import path
from food import views

app_name="food"

urlpatterns = [
    #function based index view
    #---------------------------------------------------------------
   # path('index/', views.index , name='index'),

    #class based index view
    #---------------------------------------------------------------
    path('index/', views.IndexClassView.as_view() , name='index'),

    #function based detail view
    #---------------------------------------------------------------
   # path("detail/<int:item_id>/",views.detail,name="detail"),

    #class based detail view
    #---------------------------------------------------------------
    path("detail/<int:pk>/",views.FoodDetail.as_view(),name="detail"),

    #function based create item view
    #---------------------------------------------------------------
   # path('add/', views.CreateItem, name='create_item'),

    #class based create item view
    #---------------------------------------------------------------
    path('add/', views.CreateView.as_view(), name='create_item'),

    #function based update item view
    #---------------------------------------------------------------
    path('update/<int:item_id>/',views.UpdateItem, name='update_item'),

    #function based delete item view
    #---------------------------------------------------------------
    path('delete/<int:item_id>/',views.DeleteItem,name='delete_item'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as userviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('users/', include('users.urls')),
    path('register/', userviews.register, name='register'),
    path('login/',userviews.login_view, name='login'),
    path('logout/',userviews.logout_view, name='logout'),
    path('profile/',userviews.ProfilePage, name='profile'),
]

mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Item(models.Model):
    rest_owner = models.ForeignKey(User, on_delete=models.CASCADE, default=1 )
    prod_code = models.IntegerField(default=100)
    added_by = models.CharField(max_length=50, default='user')
    item_name=models.CharField(max_length=50)
    item_desc=models.CharField(max_length=500, default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque nisi a adipisci sapiente culpa, ipsum quos et facilis? Obcaecati doloremque sit non facilis molestiae eaque necessitatibus dolorem exercitationem saepe corrupti?')
    item_price=models.IntegerField()
    item_image=models.CharField(
        default='https://assets.materialup.com/uploads/b03b23aa-aa69-4657-aa5e-fa5fef2c76e8/preview.png',
        max_length=500
    )


    def __str__(self):
        return self.item_name




      

mysite/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from food.models import Item
from food.form import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy


# Create your views her
#function based index view
#---------------------------------------------------------------
def index(request):
    itemlist = Item.objects.all()

    context={
        'itemlist':itemlist
    }
    return render(request, 'food/home.html',context)

#class based index view
#---------------------------------------------------------------
class IndexClassView(ListView):
    model = Item
    context_object_name = 'itemlist'
    template_name = 'food/home.html'

#function based detail view
#---------------------------------------------------------------
def detail(request,item_id):
    item= Item.objects.get(id= item_id)

    context={"item":item}
    return render(request,"food/detail.html",context)

#class based detail view
#---------------------------------------------------------------
class FoodDetail(DetailView):
    model = Item
    context_object_name = 'item'
    template_name = "food/detail.html"


#function based create item view
#---------------------------------------------------------------
def CreateItem(request):

    form = ItemForm(request.POST or None)
    if request.method == 'POST':
        form.instance.added_by = request.user.username
        form.save()
        return redirect('food:index')

    context = {
        'form':form
    }
    
    return render(request, 'food/item-form.html', context)

#class based create item view
#---------------------------------------------------------------
class CreateItem(CreateView):
    model = Item
    fields = ['rest_owner','prod_code','item_name','item_desc','item_price','item_image']
    template_name = 'food/item-form.html'
    context_object_name = 'form'
    success_url = reverse_lazy('food:index')

    def form_valid(self,form):
         form.instance.added_by = self.request.user.username
         return super().form_valid(form )


#function based update item view
#---------------------------------------------------------------
def UpdateItem(request,item_id):

    item = Item.objects.get(id=item_id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:detail', item_id)

    context ={
        'form':form
}

    return render(request,'food/item-form.html',context)


#function based delete item view
#---------------------------------------------------------------
def DeleteItem(request, item_id):

    item = Item.objects.get(id=item_id)

    context ={
        'item':item
    }

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')

    return render(request,'food/item-delete.html',context)

mysite/food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="{% url 'food:index' %}" class="navbar-brand">
              FoodMart
        </a>

        <div class="navbar">
            {% if user.is_authenticated %}
            <a href="{% url 'food:create_item' %}" class="nav-item nav-link btn btn-dark">Add item</a>
            <a href="{% url 'profile' %}" class="nav-item nav-link btn btn-dark">Profile</a>
            <a href="{% url 'logout' %}" class="nav-item nav-link btn btn-dark">Logout</a>

            {% else %}
            <a href="{% url 'register' %}" class="nav-item nav-link btn btn-dark">Sign Up</a>
            <a href="{% url 'login' %}" class="nav-item nav-link btn btn-dark">Login</a>
            <a href="{% url 'logout' %}" class="nav-item nav-link btn btn-dark">Logout</a>

            {% endif %}



        </div>


    </nav>
    {% if messages %}
        {% for messages in messages %}
            <div class="alert alert-{{ messages.tags }}">
                {{ messages }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="mb-5"></div>




    {% block body %}
    {% endblock %}

    
</body>
</html>

mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}

<img src="{{ item.item_image }}" alt="">

<h1>    {{ item.item_name }}</h1>
<h1>    {{ item.item_desc }}</h1>
<h1>   {{ item.item_price }}</h1>

<div class="row">
    <div class="col-md-2 offset-md-1">
        <img clas="card" height="150px"  width="250px" src="{{ item.item_image }}">
    </div>
    <div class="col-md-4 offset-md-1">
        <h1 style="font-style: italic"> {{ item.item_name }} </h1>
        <h2 style="font-style: italic; font-size:1.3rem; text-align:justify">{{ item.item_desc }} </h2>
        <h3>$ {{ item.item_price }}</h3>
    </div>
    <div class="col-md-3 offset-md-1">
        <a href="{% url 'food:update_item' item.id %}" style="width: 80px" class="btn btn-warning">Edit</a>
        <a href="{% url 'food:delete_item' item.id %}" style="width: 80px" class="btn btn-danger">Delete</a> 
        <a href="{% url 'food:index' %}" style="width: 80px" class="btn btn-success">Back</a>
    </div>

</div>

{% endblock %}

mysite/food/templates/food/home.html
{% extends 'food/base.html' %}

{% block body %}


{% for item in itemlist %}

  <!--<ul>
    <li>
        <a href="{% url 'food:detail' item.id %}">
            {{ item.id }} |~| {{ item.item_name }} |~| {{ item.item_price}}
        </a>
    </li>
  </ul>-->
  <div class="row mb-5">
       <div class="col-md-3 offset-md-2">
        <img src="{{ item.item_image}}" class="card" height="135px" width="230px" alt="">

       </div>

       <div class="col-md-4">
        <h3 style="font-size:1.5rem">{{ item.item_name }}</h3>
        <h5 style="font-style:italic; font-size:1rem;">{{ item.item_desc | truncatewords:6 }}</h5>
        <h6>${{ item.item_price }}</h6>
        <h6 style="font-style:italic">added for: </h6>
        <h6 style="font-style:italic">added by superuser:</h6>
       </div>

       <div class="col-md-3">
        <a href="{% url 'food:detail' item.id %}" style="width: 100px" class="btn btn-success">Details</a>
       </div>


  </div>
{% endfor %}

{% endblock %}

mysite/food/templates/food/item-delete.html
{% extends 'food/base.html' %}

{% block body %}

 
<form method="POST">
    {% csrf_token %}
<h1> Are you sure you want to delete {{ item.item_name }}?</h1>
<button class="btn btn-dark" type="submit">Yes, I'm Sure</button>
<a class="btn btn-dark" href="{% url 'food:detail' item.id %}">No</a>
</form>
{% endblock %}

mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}

{% block body %}


<form method="POST">
    {% csrf_token %}

    <label>Restaurant_Owner: </label>
    {{ form.rest_owner }}

    <label>Prod Code: </label>
    {{ form.prod_code }}

    <br><label>Item Name: </label>
    {{ form.item_name }}

    <br><label>Item Description: </label>
    {{ form.item_desc }}

    <br><label>Item Price: </label>
    {{ form.item_price }}

    <br><label>Item Image: </label>
    {{ form.item_image }}

    <br><button type="submit">Save</button>
</form>

{% endblock %}